# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1c\n\x0c\x41uthResponse\x12\x0c\n\x04\x61uth\x18\x01 \x01(\x08\x32\x32\n\x0b\x41uthService\x12#\n\x04\x41uth\x12\x0c.AuthRequest\x1a\r.AuthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=14
  _globals['_AUTHREQUEST']._serialized_end=63
  _globals['_AUTHRESPONSE']._serialized_start=65
  _globals['_AUTHRESPONSE']._serialized_end=93
  _globals['_AUTHSERVICE']._serialized_start=95
  _globals['_AUTHSERVICE']._serialized_end=145
# @@protoc_insertion_point(module_scope)
#
AuthRequest = _globals['AuthRequest']
AuthResponse = _globals['AuthResponse']